name: "Close Stale Issues"

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
      - name: Close stale issues
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 20
          days-before-close: 10
          stale-issue-label: "meta/stale"
          close-issue-label: "meta/closed due to age or inactivity"
          stale-issue-message: >
            This issue has become stale because it has been open for 20 days without
            activity. Remove the label and comment or this issue will be closed in 10 days.
          close-issue-message: >
            This issue was closed due to inactivity.
